# NumPy Basics


## NumPy는 Numerical Python의 줄임말


> Numpy 제공 기능

- 빠르고 메모리를 효율적으로 사용하며, 벡터, 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarry
- 반복문을 작성할 필요없이 전체 데이터 배열에 대한 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선셩대수, 난수발생기, 푸리에 변환 기능
- C, C++, FORTRAN으로 쓰여진 코드를 통합하는 도구

In [3]:
from IPython.display import Image
from numpy.random import randn
import numpy as np

## <font color = 'red'>1. The NumPy ndarray: a multidimensional array object </font>
> 다차원 배열 객체

In [16]:
# randn
data = randn(2,3)
data  # 대괄호개수: ndim
print('data',data)

type(data.ndim)

print(data * 10)

print(data.shape)
print(data.dtype)



data [[ 0.96624099  2.10505027  1.81021783]
 [-0.46230152  0.48673344  0.05168049]]
[[ 9.66240988 21.05050265 18.10217833]
 [-4.6230152   4.86733441  0.51680487]]
(2, 3)
float64


## creating ndarrays

In [18]:
# list -> array
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(type(data1), data1)
print(type(arr1), arr1)


<class 'list'> [6, 7.5, 8, 0, 1]
<class 'numpy.ndarray'> [6.  7.5 8.  0.  1. ]


In [20]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(data2, type(data2))
print(arr2, type(data2))

print(arr2.dtype)
print(arr2.shape)


[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'list'>
int32
(2, 4)


In [26]:
# 0으로 채우기
zero = np.zeros(10)
print(zero)

one = np.ones((2,3))
print(one)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# 쓰레기값으로 쓰기
empty = np.empty((2,3,4))
print(empty)
print(empty.shape)
# 차원: element 개수-> 3차원
# 제일 안쪽 element의 개수: 4개



[[[1.28935628e-311 7.31217156e-322 0.00000000e+000 0.00000000e+000]
  [2.05833592e-312 1.16095484e-028 2.44046782e-152 4.83245960e+276]
  [1.29631049e-153 1.57732366e-052 8.48717382e+136 2.17229801e-153]]

 [[4.83245960e+276 9.15558521e+135 3.50179473e+251 2.86530681e+161]
  [2.86530675e+161 7.35874688e+223 1.07184194e+160 9.13553923e+242]
  [4.50620798e-144 4.82412328e+228 1.04718130e-142 1.23971697e+224]]]
(2, 3, 4)


In [28]:
# 파이썬 range()함수과 같은 기능 -> array
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [29]:
arr1 = np.array([1,2,3], dtype = np.float64)
print(arr1.dtype)

float64


In [32]:
arr2 = np.array([1,2,3], dtype = np.int32)
print(arr2.dtype)

int32


In [35]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

[ 3.7 -1.2 -2.6  0.5 12.9 10.1] float64 (6,)


- astype

- 형변환 함수,
- 새로운 배열 생성(data 복사)

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr, arr.dtype, arr.shape)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1] float64 (6,)
[ 3 -1 -2  0 12 10]


In [40]:
numeric_strings = np.array(['1.25', '-9.6','42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [41]:
int_array = np.arange(10)
int_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
calibers = np.array([.27, .270, .357, .380, .44,0.5], dtype = np.float64)
print(calibers)
print(calibers.dtype)

[0.27  0.27  0.357 0.38  0.44  0.5  ]
float64


In [ ]:
int_array.astype(clibers.dtype)

## Operations between arrays and scalars
 > 배열과 스칼라간의 연산

In [47]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr * arr)
print(arr - arr)
print(1/arr)
print(arr ** 0.5)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Basic indexing and slicing

> 색인과 슬라이싱 기초

In [48]:
arr = np.arange(10)
print('arr', arr)
print('arr[5]:', arr[5])
print('arr[5:8]', arr[5:8])

arr [0 1 2 3 4 5 6 7 8 9]
arr[5]: 5
arr[5:8] [5 6 7]


In [50]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [53]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[1] = 12345
print(arr)  # 슬라이스 했는데, 원본이 같이 바뀜 

[    0     1     2     3     4    12 12345    12     8     9]


In [58]:
# 원본이 바뀌지 않도록 하려면 : copy()
arr2 = arr[5:8].copy()
print(arr2)

arr2[1] = 1000
print(arr2)
print(arr) # 원봄이 바뀌지 않음

[   12 12345    12]
[  12 1000   12]
[    0     1     2     3     4    12 12345    12     8     9]


## 2차원 배열

In [66]:
# NumPy 배열에서 요소 색인하기
Image(bpc.Figure4_1)

NameError: name 'bpc' is not defined

In [67]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
print(arr2d[0,2])
print(arr2d[2,0])

3
7


## 3차원 배열


In [72]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr3d[0]= 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1,0]

array([7, 8, 9])

## Indexing with slices

- 슬라이스 색인

In [79]:
# 2차원 배열 슬라이싱
Image(bpc.Figure4_2)

NameError: name 'bpc' is not defined

In [80]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2d[1, :2]

array([4, 5])

In [85]:
arr2d[2, :1]

array([7])

In [86]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [87]:
arr2d[:2, 1:] = 1

In [88]:
arr2d 

array([[1, 1, 1],
       [4, 1, 1],
       [7, 8, 9]])

 ## Boolean indexing
 
 ### 불리언 색인
 
 
 - 값이 true에 해당하는 index 가져오기

In [94]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [92]:
data = randn(7,4)
data

array([[ 0.48439048,  0.3697663 ,  0.11166487, -0.39685176],
       [-1.11071229, -0.04778697,  0.66741279, -0.8323729 ],
       [ 0.09264865,  1.28979292,  1.22091425, -1.18524756],
       [-2.45488259, -1.00702017, -1.55308794, -0.07603892],
       [-0.64675805,  0.56971222, -1.09850115,  0.40159205],
       [ 0.10507984,  1.85747766,  0.28063227,  0.37148984],
       [-0.82967082,  0.23499013,  0.61875597, -0.68681395]])

In [95]:
names == 'Bob'  # True: 0, 3 

array([ True, False, False,  True, False, False, False])

In [97]:
data[names == 'Bob'] # 0, 3행

array([[ 0.48439048,  0.3697663 ,  0.11166487, -0.39685176],
       [-2.45488259, -1.00702017, -1.55308794, -0.07603892]])

In [98]:
data[names == 'Bob', 2:]

array([[ 0.11166487, -0.39685176],
       [-1.55308794, -0.07603892]])

In [104]:
data[names == 'Bob', 3]  # data[행, 열]

array([-0.39685176, -0.07603892])

In [105]:
data[names != 'Bob', 3]

array([-0.8323729 , -1.18524756,  0.40159205,  0.37148984, -0.68681395])

In [100]:
#~(틸드) not의 의미
data[~ (names == 'Bob')]

array([[-1.11071229, -0.04778697,  0.66741279, -0.8323729 ],
       [ 0.09264865,  1.28979292,  1.22091425, -1.18524756],
       [-0.64675805,  0.56971222, -1.09850115,  0.40159205],
       [ 0.10507984,  1.85747766,  0.28063227,  0.37148984],
       [-0.82967082,  0.23499013,  0.61875597, -0.68681395]])

In [108]:
mask = (names == 'Bob') | (names == 'Will')

print(mask)

[ True False  True  True  True False False]


In [109]:
data[mask]

array([[ 0.48439048,  0.3697663 ,  0.11166487, -0.39685176],
       [ 0.09264865,  1.28979292,  1.22091425, -1.18524756],
       [-2.45488259, -1.00702017, -1.55308794, -0.07603892],
       [-0.64675805,  0.56971222, -1.09850115,  0.40159205]])

In [111]:
data[data<0] = 0
data

array([[0.48439048, 0.3697663 , 0.11166487, 0.        ],
       [0.        , 0.        , 0.66741279, 0.        ],
       [0.09264865, 1.28979292, 1.22091425, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.56971222, 0.        , 0.40159205],
       [0.10507984, 1.85747766, 0.28063227, 0.37148984],
       [0.        , 0.23499013, 0.61875597, 0.        ]])

In [112]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.66741279, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.10507984, 1.85747766, 0.28063227, 0.37148984],
       [0.        , 0.23499013, 0.61875597, 0.        ]])

## Fancy indexting

> 팬시 색인

- 팬시 색인은 정수 배열을 사용한 색인을 설명하기 위해 numpy에서 차용한 단어
- 인덱스로 list를 사용

In [113]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정한 순서로 로우를 선택하고 싶으면 원하는 순서가 담긴 리스트나 ndarray를 넘기기

In [114]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [115]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

- 다차원 색인 배열을 넘기는 것은 조금 다르게 동작
- 각각의 색인 튜틀에 대응하는 1차원 배열을 선택한 후, reshape시킨다

In [119]:
# more on reshape in chapter 12
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [120]:
# (1,0),(5,3), (7,1), (2,2)에 대응하는 요소 선택
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [124]:
# 행렬을 원하는 부분을 원하는 순서로 정렬하기
print(arr[[1,5,7,2]])

print(arr[[1,5,7,2]][:, [0,3,1,2]])

#np.ix_() 원하는 대로 행 순서, 열 순서 바꾸기
print(arr[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## Transposing arrays and swapping axes

> 배열 전치와 축 바꾸기

- 배열 전치: 데이터를 복사하지 알고, 데이터 모양이 바뀐 뷰를 반환하는 특별한 기능
- 방법
- 1. tranopose(): 축 번호를 받아서 치환한다
- 2. A.T


In [125]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [127]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [134]:
arr = np.random.randn(3, 3)

arr

array([[ 1.29032081,  0.16181082, -0.39395795],
       [ 0.86518915,  0.77191582, -0.64489607],
       [-0.49939592,  0.66732623,  1.51569319]])

In [136]:
# 행렬식 곱하기
np.dot(arr.T, arr)

array([[ 2.66287633,  0.54338105, -1.82322022],
       [ 0.54338105,  1.06736107,  0.44990969],
       [-1.82322022,  0.44990969,  2.86841964]])

In [140]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

print(arr.transpose((1, 0, 2)))  # 파라미터: axis 축의 인덱스

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [141]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])