In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.Series([1,2,3,4], index = ['a','b','c','d'])

a

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
type(a)

pandas.core.series.Series

In [4]:
a.shape

(4,)

In [5]:
a.values

array([1, 2, 3, 4], dtype=int64)

In [6]:

a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
a['a']

1

In [8]:
a[:]

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
a[::2]

a    1
c    3
dtype: int64

In [10]:
a['a'] = 2
a

a    2
b    2
c    3
d    4
dtype: int64

In [11]:
a[a>2]

c    3
d    4
dtype: int64

In [13]:
a[a>2] = 10
a


a     2
b     2
c    10
d    10
dtype: int64

In [14]:
sr1 = pd.Series(np.arange(1, 13, dtype = np.int))
sr1

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int32

In [15]:
sr1.sum()

78

In [16]:
sr1.mean()

6.5

In [18]:

sr1.std()

3.605551275463989

In [19]:
sr1.max()


12

In [26]:
sr1 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
sr2 = pd.Series([5,6,7,8], index = ['a','b','c','d'])

In [27]:
sr1 + sr2

a     6
b     8
c    10
d    12
dtype: int64

In [28]:

sr1 - sr2

a   -4
b   -4
c   -4
d   -4
dtype: int64

In [29]:
sr1 / sr2

a    0.200000
b    0.333333
c    0.428571
d    0.500000
dtype: float64

In [33]:
 # 내적
sr1.dot(sr2)

70

In [34]:
pd.concat((sr1, sr2)) 

a    1
b    2
c    3
d    4
a    5
b    6
c    7
d    8
dtype: int64

In [42]:
sr1 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
sr2 = pd.Series([5,6,7,8,9], index = ['a','b','c','d','e'])

In [36]:
sr1 + sr2

a     6.0
b     8.0
c    10.0
d    12.0
e     NaN
dtype: float64

In [37]:
sr1 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
sr2 = pd.Series([1,2,3,4], index = ['d','c','b','a'])

sr1 + sr2

a    5
b    5
c    5
d    5
dtype: int64

In [43]:
sr3 = sr1 + sr2

In [44]:
sr3

a     6.0
b     8.0
c    10.0
d    12.0
e     NaN
dtype: float64

In [45]:
# null값 확인
pd.isnull(sr3)

a    False
b    False
c    False
d    False
e     True
dtype: bool

In [46]:
sr3[pd.notnull(sr3)]

a     6.0
b     8.0
c    10.0
d    12.0
dtype: float64

In [47]:
sr3

a     6.0
b     8.0
c    10.0
d    12.0
e     NaN
dtype: float64

In [48]:
sr3.index.name = 'name'

In [49]:
sr3

name
a     6.0
b     8.0
c    10.0
d    12.0
e     NaN
dtype: float64

In [55]:
data = {'score1' : ['91','94','97','100'],
       'score2' : np.arange(100, 90, -3)}
data

{'score1': ['91', '94', '97', '100'], 'score2': array([100,  97,  94,  91])}

In [57]:
df1 = pd.DataFrame(data = data , index = ['a','b','c','d'])
df1

score1  score2
a     91     100
b     94      97
c     97      94
d    100      91

In [59]:
data = np.arange(8).reshape(4, 2)
df1 = pd.DataFrame(data, index = ['a','b','c','d'])

df1

0  1
a  0  1
b  2  3
c  4  5
d  6  7

In [63]:
data = np.arange(1, 13, dtype = np.int).reshape(3, 4)
df1 = pd.DataFrame(data, index = ['a','b','c'], 
                   columns = ['score1','score2','score3','score4'])
df1

score1  score2  score3  score4
a       1       2       3       4
b       5       6       7       8
c       9      10      11      12

In [64]:
df1.iloc[1, 2]

7

In [65]:
df1.iloc[1][2]

7

In [66]:
df1.loc['b','score3']

7

In [67]:
df1.score3[1]

7

In [68]:
df1

score1  score2  score3  score4
a       1       2       3       4
b       5       6       7       8
c       9      10      11      12

In [69]:
df1.iloc[[1,2,1],[0,2,3]]

score1  score3  score4
b       5       7       8
c       9      11      12
b       5       7       8

In [73]:
mat1 = np.arange(1, 13,dtype = np.int).reshape(3, 4)
df1 = pd.DataFrame(mat1)
df1

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [74]:
df1.sum(axis= 0)

0    15
1    18
2    21
3    24
dtype: int64

In [75]:
df1.sum(axis = 1)

0    10
1    26
2    42
dtype: int64

In [77]:
mat3 = np.arange(13, 25, dtype = np.int).reshape(3, 4)
df2 = pd.DataFrame(mat3)
df2


0   1   2   3
0  13  14  15  16
1  17  18  19  20
2  21  22  23  24

In [78]:
df1 + df2

0   1   2   3
0  14  16  18  20
1  22  24  26  28
2  30  32  34  36

In [79]:
df1 - df2

0   1   2   3
0 -12 -12 -12 -12
1 -12 -12 -12 -12
2 -12 -12 -12 -12

In [80]:
df1* df2

0    1    2    3
0   13   28   45   64
1   85  108  133  160
2  189  220  253  288

In [81]:
df2.T

0   1   2
0  13  17  21
1  14  18  22
2  15  19  23
3  16  20  24

In [82]:
df1.dot(df2.T)

0    1    2
0  150  190  230
1  382  486  590
2  614  782  950

In [83]:

pd.concat((df1, df2), axis = 0)

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
0  13  14  15  16
1  17  18  19  20
2  21  22  23  24

In [84]:
pd.concat((df1, df2), axis = 1)

0   1   2   3   0   1   2   3
0  1   2   3   4  13  14  15  16
1  5   6   7   8  17  18  19  20
2  9  10  11  12  21  22  23  24

In [85]:

pd.concat((df1, df2), axis = 1).loc[:,1]

1   1
0   2  14
1   6  18
2  10  22

In [88]:
mat1 = np.arange(1, 16).reshape(3, 5)
print(mat1)
df1 = pd.DataFrame(mat1, index = ['a','b','c'],
                  columns = ['score1','score2','score3','score4','score5'])
df1

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


score1  score2  score3  score4  score5
a       1       2       3       4       5
b       6       7       8       9      10
c      11      12      13      14      15

In [95]:
mat2 = np.arange(3, 15).reshape(3, 4)
df2 = pd.DataFrame(mat2, index = ['a','b','c'],
                  columns = ['score3','score4','score5','score6'])
df2

score3  score4  score5  score6
a       3       4       5       6
b       7       8       9      10
c      11      12      13      14

In [96]:
df1 + df2

score1  score2  score3  score4  score5  score6
a     NaN     NaN       6       8      10     NaN
b     NaN     NaN      15      17      19     NaN
c     NaN     NaN      24      26      28     NaN

In [97]:

df3 = df1 + df2
df3

score1  score2  score3  score4  score5  score6
a     NaN     NaN       6       8      10     NaN
b     NaN     NaN      15      17      19     NaN
c     NaN     NaN      24      26      28     NaN

In [98]:
df3.isnull()

score1  score2  score3  score4  score5  score6
a    True    True   False   False   False    True
b    True    True   False   False   False    True
c    True    True   False   False   False    True

In [99]:
df3.where(df3.notnull())

score1  score2  score3  score4  score5  score6
a     NaN     NaN       6       8      10     NaN
b     NaN     NaN      15      17      19     NaN
c     NaN     NaN      24      26      28     NaN

In [100]:
df3.where(df3.notnull())

score1  score2  score3  score4  score5  score6
a     NaN     NaN       6       8      10     NaN
b     NaN     NaN      15      17      19     NaN
c     NaN     NaN      24      26      28     NaN

In [102]:
df3.where(df3.notnull()).dropna(axis = 0)

Empty DataFrame
Columns: [score1, score2, score3, score4, score5, score6]
Index: []

In [104]:
df3.where(df3.notnull()).dropna(axis = 1)

score3  score4  score5
a       6       8      10
b      15      17      19
c      24      26      28

In [105]:
df3

score1  score2  score3  score4  score5  score6
a     NaN     NaN       6       8      10     NaN
b     NaN     NaN      15      17      19     NaN
c     NaN     NaN      24      26      28     NaN

In [106]:
df3.index.name = 'name'
df3

score1  score2  score3  score4  score5  score6
name                                                
a        NaN     NaN       6       8      10     NaN
b        NaN     NaN      15      17      19     NaN
c        NaN     NaN      24      26      28     NaN

In [110]:

df3.columns.name = 'exam'
df3

exam  score1  score2  score3  score4  score5  score6
name                                                
a        NaN     NaN       6       8      10     NaN
b        NaN     NaN      15      17      19     NaN
c        NaN     NaN      24      26      28     NaN