In [1]:
# 5. Logistic(regression) Classifier

In [2]:
from tqdm import tqdm_notebook


### 로지스틱 회귀 (Logistic regression)

위키피디어 : 로지스틱 회귀 (Logistic regression)

> 로지스틱 회귀
- D.R.Cox가 1958년에 제안한 확률 모델로서 독립 변수의 선형 결합을 이용하여 사건의 발생 가능성을 예측하는데 사용되는 통계 기법이다.
- 로지스틱 회귀는 선형 회귀 분석과는 다르게 종속 변수가 범주형 데이터를 대상으로 하며 입력 데이터가 주어졌을 때 해당 데이터의 결과가 특정 분류로 나뉘기 때문에 
- 일종의 분류 (classification) 기법으로도 볼 수 있다.

> 로지스틱 함수
- 로지스틱 모형 식은 독립 변수가 [-∞,∞]의 어느 숫자이든 상관 없이 종속 변수 또는 결과 값이 항상 범위 [0,1] 사이에 있도록 한다.
- 이는 오즈비(odds ratio)를 로짓(logit) 변환을 수행함으로써 얻어진다

> Logistic Regression Classifier

- Logistic Model : holehouse.org / Logistic Regression
- Cost Function : Logistic Regression Cost Function
$$ H(X) = \frac{1}{1 + e^-W^TX} $$
$$ cost(W) = -\frac{1}{m} \sum y log(H(x)) + (1-y)(log(1 - H(x)) $$
$$ W := W - α \frac{σ}{σW} cost(W) $$

- 시그모이드 함수

In [13]:

import tensorflow as tf

tf.set_random_seed(777)  # for reproducibility

# Training Data 2dim: x1(hours), x2(attendence)
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]  
# Result Data : y(0:fail or 1:pass)
y_data = [[0], [0], [0], [1], [1], [1]]                     

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

Tensor("Cast_2:0", shape=(?, 1), dtype=float32)


In [12]:
# 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict = {X: x_data, Y: y_data})
        if step % 200 == 0 or step < 10:
            print('step : {} ,cost : {}'.format(step, cost_val))
            
    # accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})

step : 0 ,cost : 3.363095283508301
step : 1 ,cost : 3.3407506942749023
step : 2 ,cost : 3.318399667739868
step : 3 ,cost : 3.2960402965545654
step : 4 ,cost : 3.273649215698242
step : 5 ,cost : 3.251307725906372
step : 6 ,cost : 3.228942632675171
step : 7 ,cost : 3.206615686416626
step : 8 ,cost : 3.184260606765747
step : 9 ,cost : 3.161933183670044
step : 200 ,cost : 0.5485365986824036
step : 400 ,cost : 0.5159369111061096
step : 600 ,cost : 0.49320507049560547
step : 800 ,cost : 0.47366562485694885
step : 1000 ,cost : 0.45606350898742676
step : 1200 ,cost : 0.4397983253002167
step : 1400 ,cost : 0.42456284165382385
step : 1600 ,cost : 0.41018804907798767
step : 1800 ,cost : 0.39657315611839294
step : 2000 ,cost : 0.3836517632007599
step : 2200 ,cost : 0.37137570977211
step : 2400 ,cost : 0.35970571637153625
step : 2600 ,cost : 0.34860798716545105
step : 2800 ,cost : 0.33805158734321594
step : 3000 ,cost : 0.3280077874660492
step : 3200 ,cost : 0.3184490203857422
step : 3400 ,cost : 0

In [14]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    h = h, c = c, a = a
))

# Hypothesis: 
[[0.03269771]
 [0.16141716]
 [0.31410128]
 [0.7771952 ]
 [0.93690586]
 [0.9792773 ]] 

# Correct (Y): 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 1.0


## Classifiying diabetes

### 당뇨병을 예측하는 실습 예제
- 예측값이 1이면 당뇨병 o
- 예측값이 0이면 당요병 x

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv("./data/data-03-diabetes.csv", header=None)
df.head(10)

0         1         2         3         4         5         6  \
0 -0.294118  0.487437  0.180328 -0.292929  0.000000  0.001490 -0.531170   
1 -0.882353 -0.145729  0.081967 -0.414141  0.000000 -0.207153 -0.766866   
2 -0.058824  0.839196  0.049180  0.000000  0.000000 -0.305514 -0.492741   
3 -0.882353 -0.105528  0.081967 -0.535354 -0.777778 -0.162444 -0.923997   
4  0.000000  0.376884 -0.344262 -0.292929 -0.602837  0.284650  0.887276   
5 -0.411765  0.165829  0.213115  0.000000  0.000000 -0.236960 -0.894962   
6 -0.647059 -0.216080 -0.180328 -0.353535 -0.791962 -0.076006 -0.854825   
7  0.176471  0.155779  0.000000  0.000000  0.000000  0.052161 -0.952178   
8 -0.764706  0.979899  0.147541 -0.090909  0.283688 -0.090909 -0.931682   
9 -0.058824  0.256281  0.573770  0.000000  0.000000  0.000000 -0.868488   

          7  8  
0 -0.033333  0  
1 -0.666667  1  
2 -0.633333  0  
3  0.000000  1  
4 -0.600000  0  
5 -0.700000  1  
6 -0.833333  0  
7 -0.733333  1  
8  0.066667  0  
9  0.100000  0

In [19]:
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('./data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# print(x_data.shape, y_data.shape)
print(" x_data.shape : {x_shape} \n y_data.shape : {y_shape}".format(
        x_shape = x_data.shape, 
        y_shape = y_data.shape
    ))

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

 x_data.shape : (759, 8) 
 y_data.shape : (759, 1)


In [20]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})       
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))    

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})

Step : 0 	 Cost : 0.8197465538978577
Step : 1 	 Cost : 0.8183177709579468
Step : 2 	 Cost : 0.8169015049934387
Step : 3 	 Cost : 0.815497875213623
Step : 4 	 Cost : 0.8141066431999207
Step : 5 	 Cost : 0.8127278685569763
Step : 6 	 Cost : 0.8113610148429871
Step : 7 	 Cost : 0.8100065588951111
Step : 8 	 Cost : 0.8086640238761902
Step : 9 	 Cost : 0.8073333501815796
Step : 200 	 Cost : 0.6836077570915222
Step : 400 	 Cost : 0.649115800857544
Step : 600 	 Cost : 0.6298925876617432
Step : 800 	 Cost : 0.6145535111427307
Step : 1000 	 Cost : 0.6013211607933044
Step : 1200 	 Cost : 0.5897302627563477
Step : 1400 	 Cost : 0.57952880859375
Step : 1600 	 Cost : 0.5705204010009766
Step : 1800 	 Cost : 0.5625402331352234
Step : 2000 	 Cost : 0.5554481148719788
Step : 2200 	 Cost : 0.5491243600845337
Step : 2400 	 Cost : 0.54346764087677
Step : 2600 	 Cost : 0.5383915305137634
Step : 2800 	 Cost : 0.5338220000267029
Step : 3000 	 Cost : 0.529696524143219
Step : 3200 	 Cost : 0.5259606242179871
S

In [21]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    # h = h, c = c, a = a
    h = h[:20], c = c[:20], a = a
))

# Hypothesis: 
[[0.46885797]
 [0.9420241 ]
 [0.21832967]
 [0.9370388 ]
 [0.3682405 ]
 [0.73513234]
 [0.93256164]
 [0.5787471 ]
 [0.21357426]
 [0.50672185]
 [0.66974866]
 [0.16735256]
 [0.39112782]
 [0.41010594]
 [0.76868975]
 [0.43411243]
 [0.7233062 ]
 [0.81862617]
 [0.7976199 ]
 [0.5760708 ]] 

# Correct (Y): 
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 0.7747035622596741
